# Generated by Django 5.1.1 on 2024-10-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_evento_historialevento'),
    ]

    operations = [
    ]
