# Generated by Django 5.1.1 on 2024-10-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_historialevento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionpermisos',
            name='clave_sistema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verificacionpermisos',
            name='critico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificacionpermisos',
            name='tipo_permiso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='verificacionpermisos',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
