# Generated by Django 5.1.1 on 2024-10-20 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_remove_evento_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialevento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificacionpermisos',
            name='clave_sistema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='verificacionpermisos',
            name='critico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificacionpermisos',
            name='tipo_permiso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='capturaspantalla',
            name='ruta_captura',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='numero',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='modelo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='evento',
            name='detalles',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='ruta_foto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grabacionesllamadas',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grabacionespantalla',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historialevento',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialevento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historialevento',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='llamadas',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='numero',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verificacionpermisos',
            name='estado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='ruta_video',
            field=models.CharField(max_length=100),
        ),
    ]
