# Generated by Django 5.1.1 on 2024-10-22 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_remove_capturaspantalla_ruta_captura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotos',
            name='ruta_foto',
        ),
        migrations.AddField(
            model_name='fotos',
            name='archivo_foto',
            field=models.ImageField(default='fotos/default.jpg', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fotos',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='FotosDispositivo',
        ),
    ]
