# Generated by Django 5.1.1 on 2024-10-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_rename_estado_verificacionpermisos_estado_permiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacionpermisos',
            name='estado_permiso',
            field=models.BooleanField(default=False),
        ),
    ]
