# Generated by Django 5.1.1 on 2024-11-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_alter_verificacionpermisos_estado_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacionpermisos',
            name='estado_permiso',
            field=models.BooleanField(),
        ),
    ]
