# Generated by Django 5.1.1 on 2024-11-14 04:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_alter_verificacionpermisos_estado_permiso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificacionpermisos',
            name='clave_sistema',
        ),
        migrations.RemoveField(
            model_name='verificacionpermisos',
            name='tipo_permiso',
        ),
        migrations.AlterField(
            model_name='verificacionpermisos',
            name='fecha_verificacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='verificacionpermisos',
            name='permiso',
            field=models.CharField(choices=[('READ_CALENDAR', 'Calendario'), ('POST_NOTIFICATIONS', 'Notificaciones'), ('CAMERA', 'Cámara'), ('READ_CONTACTS', 'Leer Contactos'), ('RECORD_AUDIO', 'Grabar Audio'), ('READ_CALL_LOG', 'Registro de Llamadas'), ('READ_SMS', 'Leer SMS'), ('ACCESS_FINE_LOCATION', 'Ubicación Precisa'), ('READ_MEDIA_IMAGES', 'Fotos y Videos'), ('READ_MEDIA_AUDIO', 'Música y Audio')], max_length=100),
        ),
    ]
