# Generated by Django 5.1.1 on 2024-11-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0018_remove_verificacionpermisos_clave_sistema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificacionpermisos',
            name='tipo_permiso',
            field=models.CharField(blank=True, choices=[('READ_CALENDAR', 'Calendario'), ('POST_NOTIFICATIONS', 'Notificaciones'), ('CAMERA', 'Cámara'), ('READ_CONTACTS', 'Leer Contactos'), ('RECORD_AUDIO', 'Grabar Audio'), ('READ_CALL_LOG', 'Registro de Llamadas'), ('READ_SMS', 'Leer SMS'), ('ACCESS_FINE_LOCATION', 'Ubicación Precisa'), ('READ_MEDIA_IMAGES', 'Fotos y Videos'), ('READ_MEDIA_AUDIO', 'Música y Audio')], max_length=100, null=True),
        ),
    ]
