# Generated by Django 5.1.1 on 2024-11-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_verificacionpermisos_tipo_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='tipo',
            field=models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=10),
        ),
    ]
